services:
  # main_service_db:
  #   build: ./main_service_db/
  #   restart: always
  #   container_name: main_service_db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: my_password
  #     POSTGRES_DB: main_service_soa
  #   ports:
  #     - "2345:5432"

  # main_service:
  #   build: ./main_service
  #   environment:
  #     DATABASE_URL: postgres://postgres:my_password@main_service_db:5432/main_service_soa
  #   command: sh -c "sleep 10s; cargo run -- 4000"
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - main_service_db

  tasks_service_db:
    build: ./tasks_service_db/
    restart: always
    container_name: tasks_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: tasks_service_soa
    # ports:
    #   - "2346:5432"

  tasks_service:
    build: ./tasks_service
    environment:
      DATABASE_HOST: tasks_service_db
      DATABASE_PORT: 5432
      DATABASE_NAME: tasks_service_soa
      DATABASE_USER: postgres
      DATABASE_PASSWORD: my_password
    command: sh -c "ls ; sleep 10s ; python3 server.py"
    ports:
      - "23456:50051"
    depends_on:
      - tasks_service_db
