services:
  db:
    build: ./main_service_db/
    restart: always
    container_name: main_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_service_soa
      POSTGRES_PORT: 2345
    ports:
      - "2345:2345"

  server:
    build: ./main_service
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:2345/main_service_soa
    command: sh -c "cargo run -- 4000"
    ports:
      - "4000:4000"
    depends_on:
      - db
