###
POST http://127.0.0.1:4000/signup
Content-Type: application/json

{
    "username": "alex1",
    "password": "alex1990*A"
}

###
POST http://127.0.0.1:4000/login
Content-Type: application/json

{
    "username": "alex1",
    "password": "alex1990*A"
}

###
POST http://127.0.0.1:4000/create_task
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhbGV4MSIsImV4cCI6MTcxNzg2MTM4Nn0.vdZWSDSqN-ZwisNBba5ZfzlCFD8WW0k02clvtFwsdXc
Content-Type: application/json

{
    "text": "Task text"
}

###
GET http://127.0.0.1:4000/get_task
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhbGV4MSIsImV4cCI6MTcxNzg2MTM4Nn0.vdZWSDSqN-ZwisNBba5ZfzlCFD8WW0k02clvtFwsdXc
Content-Type: application/json

{
    "task_id": 1
}

###
PUT http://127.0.0.1:4000/update_task
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhbGV4MSIsImV4cCI6MTcxNzg2MTM4Nn0.vdZWSDSqN-ZwisNBba5ZfzlCFD8WW0k02clvtFwsdXc
Content-Type: application/json

{
    "task_id": 3,
    "new_text": "New task text"
}

###
DELETE http://127.0.0.1:4000/delete_task
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhbGV4MSIsImV4cCI6MTcxNzg2MTM4Nn0.vdZWSDSqN-ZwisNBba5ZfzlCFD8WW0k02clvtFwsdXc
Content-Type: application/json

{
    "task_id": 2
}

###
GET http://127.0.0.1:4000/list_tasks
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhbGV4MSIsImV4cCI6MTcxNzg2MTM4Nn0.vdZWSDSqN-ZwisNBba5ZfzlCFD8WW0k02clvtFwsdXc
Content-Type: application/json

{
    "offset": 0,
    "limit": 100
}
