###
POST http://127.0.0.1:4000/signup
Content-Type: application/json

{
    "username": "alex1",
    "password": "alex1990*A"
}

###
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "username": "alex1",
    "password": "alex1990*A"
}

###
POST http://127.0.0.1:5000/create_task
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTgsInVzZXJuYW1lIjoiYWxleDEiLCJleHAiOjE3MTc4NTgwNjN9.NDFbHyfeLviJtBmmVl5ncDHleirmmz_gawetCyKTOm8
Content-Type: application/json

{
    "text": "Task text"
}

###
GET http://127.0.0.1:4000/get_task
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTgsInVzZXJuYW1lIjoiYWxleDEiLCJleHAiOjE3MTc4NTgwNjN9.NDFbHyfeLviJtBmmVl5ncDHleirmmz_gawetCyKTOm8
Content-Type: application/json

{
    "task_id": 149
}

###
PUT http://127.0.0.1:4000/update_task
Authorization: 
Content-Type: application/json

{
    "task_id": ,
    "new_text": "Task text"
}

###
DELETE http://127.0.0.1:4000/delete_task
Authorization: 
Content-Type: application/json

{
    "task_id": ""
}

###
GET http://127.0.0.1:4000/list_tasks
Authorization: 
Content-Type: application/json

{
    "offset": "0",
    "limit": "100"
}
