###
POST http://127.0.0.1:5000/create_user
Content-Type: application/json

{
    "username": "alex",
    "password": "alex1990"
}

###
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "username": "doesn't exist",
    "password": "password"
}

###
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "username": "alex",
    "password": "alex1990"
}

###
PUT http://127.0.0.1:5000/update_user_data
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzEwNTM3NDkxfQ.Pts2xE49XF7VkLIJnhKGLtKD_xvsfs96AJz27z2L-Yk
Content-Type: application/json

{
    "firstname": "qqqqqqqqqqqqqqqqqqqq",
    "lastname": "www"
}
