###
POST http://127.0.0.1:4000/signup
Content-Type: application/json

{
    "username": "alex",
    "password": "alex1990"
}

###
POST http://127.0.0.1:4000/login
Content-Type: application/json

{
    "username": "doesn't exist",
    "password": "password"
}

###
POST http://127.0.0.1:4000/login
Content-Type: application/json

{
    "username": "alex",
    "password": "alex1990"
}

###
PUT http://127.0.0.1:4000/update_user_data
Authorization: 
Content-Type: application/json

{
    "first_name": "qqqqqqqqqqqqqqqqqqqq",
    "last_name": "www"
}

###
GET http://127.0.0.1:4000/get_user_data
Authorization: 
Content-Type: application/json
