FROM python:3.9-slim
WORKDIR /app
COPY server.py requirements.txt tasks.proto /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 50051
RUN apt update && apt install -y --no-install-recommends protobuf-compiler
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. tasks.proto
