# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"\x0e\n\x0c\x45mptyMessage\"4\n\x11\x43reateTaskRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"%\n\x12\x43reateTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\"G\n\x11UpdateTaskRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\x12\x10\n\x08new_text\x18\x03 \x01(\t\"5\n\x11\x44\x65leteTaskRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\"2\n\x0eGetTaskRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\"C\n\x0fGetTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x11\n\tauthor_id\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t\"B\n\x10ListTasksRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"/\n\x11ListTasksResponse\x12\x1a\n\x05tasks\x18\x01 \x03(\x0b\x32\x0b.tasks.Task\"8\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x11\n\tauthor_id\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t2\xc4\x02\n\x0bTaskService\x12\x41\n\nCreateTask\x12\x18.tasks.CreateTaskRequest\x1a\x19.tasks.CreateTaskResponse\x12;\n\nUpdateTask\x12\x18.tasks.UpdateTaskRequest\x1a\x13.tasks.EmptyMessage\x12;\n\nDeleteTask\x12\x18.tasks.DeleteTaskRequest\x1a\x13.tasks.EmptyMessage\x12\x38\n\x07GetTask\x12\x15.tasks.GetTaskRequest\x1a\x16.tasks.GetTaskResponse\x12>\n\tListTasks\x12\x17.tasks.ListTasksRequest\x1a\x18.tasks.ListTasksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYMESSAGE']._serialized_start=22
  _globals['_EMPTYMESSAGE']._serialized_end=36
  _globals['_CREATETASKREQUEST']._serialized_start=38
  _globals['_CREATETASKREQUEST']._serialized_end=90
  _globals['_CREATETASKRESPONSE']._serialized_start=92
  _globals['_CREATETASKRESPONSE']._serialized_end=129
  _globals['_UPDATETASKREQUEST']._serialized_start=131
  _globals['_UPDATETASKREQUEST']._serialized_end=202
  _globals['_DELETETASKREQUEST']._serialized_start=204
  _globals['_DELETETASKREQUEST']._serialized_end=257
  _globals['_GETTASKREQUEST']._serialized_start=259
  _globals['_GETTASKREQUEST']._serialized_end=309
  _globals['_GETTASKRESPONSE']._serialized_start=311
  _globals['_GETTASKRESPONSE']._serialized_end=378
  _globals['_LISTTASKSREQUEST']._serialized_start=380
  _globals['_LISTTASKSREQUEST']._serialized_end=446
  _globals['_LISTTASKSRESPONSE']._serialized_start=448
  _globals['_LISTTASKSRESPONSE']._serialized_end=495
  _globals['_TASK']._serialized_start=497
  _globals['_TASK']._serialized_end=553
  _globals['_TASKSERVICE']._serialized_start=556
  _globals['_TASKSERVICE']._serialized_end=880
# @@protoc_insertion_point(module_scope)
